### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ajinabraham** [skepticfx/hookish#1]
Is there someway to get the flow from source to sink. Like 
1. How a data flow occurred form a source to sink.
2. In between how data got changed (encoded, decoded, or some other modifications) or what all operations are done on that data.
3. Stimulate the same data flow from source to sink with <  > ' " / \ ` { } ( ) + - as data from source and see how or in what form it reaches the sink.

Btwn awesome work @nafeez !!

**Comment by skepticfx** [comment]
@ajinabraham Yes it does. But not to the level with what you'll get with hard-core taint propagation systems like Dominator. However, this would still try to find those cases where the string ends up more or less the same without altering much. I already have it now and am trying to re-write that part to make sure that the edge cases are sorted out before I want to release it. In fact, the whole Hookish! thing started a couple years back. Just trying to rewrite it completely and trying to git it. 

Am going to target mostly the modern day apps and I have a few plans for them. Thanks for raising this issue.
