### ISSUE TITLE
doesn't seeems to be working with Chormium Version 42.0.2311.90 (64-bit)

### ISSUE THREAD

**Issue by anantshri** [skepticfx/hookish#3]
I get a message " 
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/." and there is nothing found by hookish. 

IS there a video of how to use hookish might help in checking if i am wrong or if the tool is not working.

**Comment by skepticfx** [comment]
Do you get this Synchronous XMLHttpRequest error without using Hookish? Because, Hookish doesn't have to do anything with changing the async flag in the XHR object. 

Right now there is no video / doc on using this. Am working on a webapp to do that with specific examples of what Hookish can catch.

It would be great if you could tell me the webapp you got this error on. Would try to see whats going on. Unless its your internal app or something, its fine.

**Comment by anantshri** [comment]
Looks like my bad on that error message part. Its not from this extension. but even without this error there is no source / sink detected. and nothing appearing in hookish. Can you point me to a vulnerable app or some place where i can test how it is working. and compare contrast results. 
webapp i would prefer keeping confidential

**Comment by skepticfx** [comment]
Thanks for confirming that. I usually try these on JS heavy websites like Twitter, Google, Facebook. Ofc this tool wont point you the exact vulnerability as of now. But you should see a lot of stuff about the webapp without going through the code.

Let me know how it goes.

**Comment by skepticfx** [comment]
Also, make sure you type in just the domain name and not the http url. My bad, this tool is not user friendly at all now. Am working hard on that part and the docs, so people could actually use it and not just me :)

**Comment by anantshri** [comment]
Ah seems the last comment was the problem. Not just the http part people also need to remove any custom port part. as you are trapping the entire domain.

I would suggest do trapping on per origin basis and preferably via , seperated list.

and this tool does need a lot of documentation. I will be trying to use this for next couple of days and will see if i can help in any ways.

**Comment by skepticfx** [comment]
Yes! Thanks @anantshri. Documentation it is!
